//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_lines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget_lines()
        {
            this.Invoice_Budget = new HashSet<Invoice_Budget>();
        }
    
        public int bl_id { get; set; }
        public Nullable<int> budget_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual Budgets Budgets { get; set; }
        public virtual Lines Lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Budget> Invoice_Budget { get; set; }
    }
}
