//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Budgets = new HashSet<Budgets>();
        }
    
        public int employee_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> position_id { get; set; }
        public string address { get; set; }
        public string postal_code { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budgets> Budgets { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
