//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Budget
    {
        public int ib_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> bl_id { get; set; }
    
        public virtual Budget_lines Budget_lines { get; set; }
        public virtual Invoices Invoices { get; set; }
    }
}
