//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.Invoice_Budget = new HashSet<Invoice_Budget>();
        }
    
        public int invoice_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string invoice_number { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public string product_name { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> billing_entries_id { get; set; }
        public Nullable<int> tax { get; set; }
        public string description { get; set; }
        public Nullable<bool> introducted { get; set; }
    
        public virtual Billing_Entries Billing_Entries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Budget> Invoice_Budget { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
